baseURL = "https://geigeviolins.com/"
languageCode = "en-us"
title = "GEIGE"

# Site configuration
copyright = "GEIGE"
author = "Rakesh R"

# Build configuration
buildDrafts = false
buildFuture = false
buildExpired = false

# Content configuration
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"
archetypeDir = "archetypes"

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

# Menu configuration
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Products"
  url = "/products/"
  weight = 2

[[menu.main]]
  name = "Contact Us"
  url = "/contact/"
  weight = 3

[[menu.main]]
  name = "About Us"
  url = "/about/"
  weight = 4

# Parameters
[params]
  description = "GEIGE - violins and accessories brand."
  keywords = ["violins", "violin bowa", "music instruments shop", "keyboards"]
  favicon = "/favicon.ico"

# Social media
[[params.social]]
  name = "Twitter"
  url = "https://twitter.com/atmoslab"

[[params.social]]
  name = "LinkedIn"
  url = "https://linkedin.com/company/atmoslab"

[[params.social]]
  name = "GitHub"
  url = "https://github.com/atmoslab"
